import os
import re
import unicodedata
import json
import hashlib
import math
from uuid import uuid4

import psycopg2
from flask import Flask, flash, redirect, render_template, request, url_for
from psycopg2 import sql

app = Flask(__name__)
app.secret_key = os.getenv("FLASK_SECRET_KEY", "dev-secret-change-me")

PROJECTS_TABLE = "project"

DEFAULT_CHUNK_OPTIONS = {
    "chunkMaxTokens": 350,
    "chunkOverlapTokens": 50,
    "hardMaxTokens": 420,
    "headingMaxLevel": 3,
    "tokenEstimator": "words",
    "charsPerToken": 4,
}

CHAT_RATING_FIELDS = (
    "rating_relevance",
    "rating_accuracy",
    "rating_clarity",
    "rating_completeness",
    "rating_helpfulness",
)

CHAT_RATING_LABELS = {
    "rating_relevance": "Pertinence",
    "rating_accuracy": "Exactitude",
    "rating_clarity": "Clarte",
    "rating_completeness": "Completude",
    "rating_helpfulness": "Utilite",
}


def get_db_connection():
    return psycopg2.connect(
        host=os.getenv("POSTGRES_HOST", "db"),
        port=os.getenv("POSTGRES_PORT", "5432"),
        dbname=os.getenv("POSTGRES_DB", "dataswarehouse"),
        user=os.getenv("POSTGRES_USER", "postgres"),
        password=os.getenv("POSTGRES_PASSWORD", "postgres"),
    )


def to_slug(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", ascii_value.lower()).strip("_")
    slug = slug[:50].strip("_")

    if not slug:
        raise ValueError("Le nom du projet ne contient pas assez de caracteres valides.")
    if slug[0].isdigit():
        slug = f"p_{slug}"

    return slug


def ensure_projects_table(cur):
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS public.project (
            uuid text PRIMARY KEY,
            project_name text NOT NULL,
            project_nameslug text NOT NULL UNIQUE,
            last_date_edit text DEFAULT 'now()' NOT NULL
        );
        """
    )


def create_project_tables(cur, slug: str):
    shard_table = f"{slug}_shard"
    chunk_table = f"{slug}_chunk"
    train_table = f"{slug}_train"
    chat_table = f"{slug}_chat"
    chat_evaluation_table = f"{slug}_chat_evaluation"

    cur.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {} (
                uuid text NOT NULL PRIMARY KEY,
                project_id text,
                source_document text,
                url_document text,
                title_document text,
                content_document text,
                autor_document text,
                last_date_edit text DEFAULT 'now()' NOT NULL
            );
            """
        ).format(sql.Identifier("public", shard_table))
    )

    cur.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {} (
                uuid text NOT NULL PRIMARY KEY,
                shard_id text,
                source_document text,
                url_document text,
                title_document text,
                content_document text,
                autor_document text,
                last_date_edit text DEFAULT 'now()' NOT NULL
            );
            """
        ).format(sql.Identifier("public", chunk_table))
    )

    cur.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {} (
                uuid text NOT NULL PRIMARY KEY,
                project_id text,
                system_content text,
                user_content text,
                assistant_content text,
                metatags text,
                upvote integer,
                downvote integer,
                last_date_edit text DEFAULT 'now()' NOT NULL
            );
            """
        ).format(sql.Identifier("public", train_table))
    )

    cur.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {} (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id varchar(255) NOT NULL,
                message jsonb NOT NULL,
                upvote integer DEFAULT 0,
                downvote integer DEFAULT 0
            );
            """
        ).format(sql.Identifier("public", chat_table))
    )

    cur.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {} (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id varchar(255) NOT NULL UNIQUE,
                rating_relevance smallint NOT NULL CHECK (rating_relevance BETWEEN 1 AND 5),
                rating_accuracy smallint NOT NULL CHECK (rating_accuracy BETWEEN 1 AND 5),
                rating_clarity smallint NOT NULL CHECK (rating_clarity BETWEEN 1 AND 5),
                rating_completeness smallint NOT NULL CHECK (rating_completeness BETWEEN 1 AND 5),
                rating_helpfulness smallint NOT NULL CHECK (rating_helpfulness BETWEEN 1 AND 5),
                rating_global numeric(3,2) GENERATED ALWAYS AS (
                    round((
                        rating_relevance +
                        rating_accuracy +
                        rating_clarity +
                        rating_completeness +
                        rating_helpfulness
                    )::numeric / 5, 2)
                ) STORED,
                comment text,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            );
            """
        ).format(sql.Identifier("public", chat_evaluation_table))
    )

    safe_slug = re.sub(r"[^a-zA-Z0-9_]", "_", slug)[:40]
    slug_hash = hashlib.sha1(slug.encode("utf-8")).hexdigest()[:8]
    safe_index_name = f"{safe_slug}_chat_eval_sid_{slug_hash}"
    cur.execute(
        sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {} (session_id);").format(
            sql.Identifier(safe_index_name),
            sql.Identifier("public", chat_evaluation_table),
        )
    )

    ensure_train_table_schema(cur, train_table)
    ensure_chat_table_schema(cur, chat_table)


def create_project(name: str):
    project_name = name.strip()
    if not project_name:
        raise ValueError("Le nom du projet est obligatoire.")

    slug = to_slug(project_name)
    project_uuid = str(uuid4())

    with get_db_connection() as conn:
        with conn.cursor() as cur:
            ensure_projects_table(cur)
            cur.execute(
                sql.SQL("SELECT 1 FROM public.{} WHERE project_nameslug = %s;").format(
                    sql.Identifier(PROJECTS_TABLE)
                ),
                (slug,),
            )
            if cur.fetchone():
                raise ValueError(f"Le slug '{slug}' existe deja.")

            create_project_tables(cur, slug)
            cur.execute(
                sql.SQL(
                    "INSERT INTO public.{} (uuid, project_name, project_nameslug) VALUES (%s, %s, %s);"
                ).format(sql.Identifier(PROJECTS_TABLE)),
                (project_uuid, project_name, slug),
            )

    return project_uuid, slug


def list_projects():
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            ensure_projects_table(cur)
            cur.execute(
                sql.SQL(
                    """
                    SELECT uuid, project_name, project_nameslug, last_date_edit
                    FROM public.{}
                    ORDER BY uuid DESC;
                    """
                ).format(sql.Identifier(PROJECTS_TABLE))
            )
            rows = cur.fetchall()

    projects = []
    for row in rows:
        projects.append(
            {
                "uuid": row[0],
                "name": row[1],
                "slug": row[2],
                "last_date_edit": row[3],
                "shard_table": f"{row[2]}_shard",
                "chunk_table": f"{row[2]}_chunk",
                "train_table": f"{row[2]}_train",
                "chat_table": f"{row[2]}_chat",
                "chat_evaluation_table": f"{row[2]}_chat_evaluation",
            }
        )
    return projects


def table_exists(cur, table_name: str) -> bool:
    cur.execute("SELECT to_regclass(%s);", (f"public.{table_name}",))
    return cur.fetchone()[0] is not None


def ensure_train_table_schema(cur, train_table: str):
    cur.execute(
        sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS metatags text;").format(
            sql.Identifier("public", train_table)
        )
    )


def ensure_chat_table_schema(cur, chat_table: str):
    cur.execute(
        sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS upvote integer DEFAULT 0;").format(
            sql.Identifier("public", chat_table)
        )
    )
    cur.execute(
        sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS downvote integer DEFAULT 0;").format(
            sql.Identifier("public", chat_table)
        )
    )


def parse_chunk_options(payload):
    options = DEFAULT_CHUNK_OPTIONS.copy()
    if not payload:
        return options

    int_fields = [
        "chunkMaxTokens",
        "chunkOverlapTokens",
        "hardMaxTokens",
        "headingMaxLevel",
        "charsPerToken",
    ]
    for field in int_fields:
        if field in payload and str(payload[field]).strip():
            options[field] = int(payload[field])

    if "tokenEstimator" in payload and str(payload["tokenEstimator"]).strip():
        options["tokenEstimator"] = str(payload["tokenEstimator"]).strip().lower()

    options["chunkMaxTokens"] = max(1, options["chunkMaxTokens"])
    options["hardMaxTokens"] = max(options["chunkMaxTokens"], options["hardMaxTokens"])
    options["chunkOverlapTokens"] = max(0, options["chunkOverlapTokens"])
    if options["chunkOverlapTokens"] >= options["chunkMaxTokens"]:
        options["chunkOverlapTokens"] = max(0, options["chunkMaxTokens"] - 1)
    options["headingMaxLevel"] = min(6, max(1, options["headingMaxLevel"]))
    options["charsPerToken"] = max(1, options["charsPerToken"])
    if options["tokenEstimator"] not in {"words", "chars"}:
        options["tokenEstimator"] = "words"

    return options


def parse_int_field(value, field_name: str, default: int = 0) -> int:
    if value is None or str(value).strip() == "":
        return default
    try:
        return int(str(value).strip())
    except ValueError as exc:
        raise ValueError(f"Le champ '{field_name}' doit etre un entier.") from exc


def normalize_metatags(raw_value) -> str:
    text_value = str(raw_value or "").strip()
    if not text_value:
        return ""

    tags = []
    seen = set()
    for raw_tag in text_value.split(","):
        normalized_tag = raw_tag.strip()
        if not normalized_tag:
            continue
        tag_key = normalized_tag.lower()
        if tag_key in seen:
            continue
        seen.add(tag_key)
        tags.append(normalized_tag)

    return ", ".join(tags)


def parse_rating_field(value, field_name: str) -> int:
    parsed = parse_int_field(value, field_name, default=0)
    if parsed < 1 or parsed > 5:
        raise ValueError(f"Le champ '{field_name}' doit etre compris entre 1 et 5.")
    return parsed


def parse_chat_message(raw_message):
    if isinstance(raw_message, dict):
        payload = raw_message
    elif isinstance(raw_message, str):
        try:
            payload = json.loads(raw_message)
        except ValueError:
            payload = {"content": raw_message}
    else:
        payload = {"content": str(raw_message)}

    if not isinstance(payload, dict):
        payload = {"content": payload}

    message_type = str(payload.get("type") or payload.get("role") or payload.get("name") or "message")
    message_content = payload.get("content")
    if isinstance(message_content, str):
        message_content = message_content.strip()
    elif message_content is None:
        message_content = ""
    else:
        message_content = json.dumps(message_content, ensure_ascii=False)

    if not message_content:
        message_content = json.dumps(payload, ensure_ascii=False)

    return {
        "type": message_type,
        "content": message_content,
        "raw": payload,
    }


def shorten_text(value: str, max_chars: int = 180) -> str:
    text = (value or "").strip()
    if len(text) <= max_chars:
        return text
    if max_chars <= 1:
        return text[:max_chars]
    if max_chars <= 3:
        return text[:max_chars]
    return f"{text[: max_chars - 3]}..."


def to_float_or_none(value):
    if value is None:
        return None
    converted = float(value)
    if math.isnan(converted):
        return None
    return converted


def find_project_by_slug(cur, project_slug: str):
    ensure_projects_table(cur)
    cur.execute(
        sql.SQL(
            """
            SELECT uuid, project_name, project_nameslug
            FROM public.{}
            WHERE project_nameslug = %s;
            """
        ).format(sql.Identifier(PROJECTS_TABLE)),
        (project_slug,),
    )
    row = cur.fetchone()
    if not row:
        raise ValueError(f"Projet introuvable pour le slug '{project_slug}'.")
    return {"uuid": row[0], "name": row[1], "slug": row[2]}


def get_project_crud_payload(project_slug: str):
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            project = find_project_by_slug(cur, project_slug)
            create_project_tables(cur, project_slug)
            shard_table = f"{project_slug}_shard"
            chunk_table = f"{project_slug}_chunk"
            train_table = f"{project_slug}_train"
            for table_name in [shard_table, chunk_table, train_table]:
                if not table_exists(cur, table_name):
                    raise ValueError(f"La table '{table_name}' est introuvable.")
            ensure_train_table_schema(cur, train_table)

            cur.execute(
                sql.SQL(
                    """
                    SELECT
                        s.uuid,
                        s.source_document,
                        s.url_document,
                        s.title_document,
                        s.content_document,
                        s.autor_document,
                        COUNT(c.uuid)::int AS chunk_count
                    FROM {} AS s
                    LEFT JOIN {} AS c
                        ON c.shard_id = s.uuid
                    GROUP BY
                        s.uuid,
                        s.source_document,
                        s.url_document,
                        s.title_document,
                        s.content_document,
                        s.autor_document
                    ORDER BY s.uuid;
                    """
                ).format(
                    sql.Identifier("public", shard_table),
                    sql.Identifier("public", chunk_table),
                )
            )
            shard_rows = cur.fetchall()

            shards = []
            for row in shard_rows:
                shards.append(
                    {
                        "uuid": row[0],
                        "source_document": row[1] or "",
                        "url_document": row[2] or "",
                        "title_document": row[3] or "",
                        "content_document": row[4] or "",
                        "autor_document": row[5] or "",
                        "chunk_count": int(row[6]),
                    }
                )

            cur.execute(
                sql.SQL(
                    """
                    SELECT
                        uuid,
                        shard_id,
                        source_document,
                        url_document,
                        title_document,
                        content_document,
                        autor_document
                    FROM {}
                    ORDER BY uuid;
                    """
                ).format(sql.Identifier("public", chunk_table))
            )
            chunk_rows = cur.fetchall()

            chunks = []
            for row in chunk_rows:
                chunks.append(
                    {
                        "uuid": row[0],
                        "shard_id": row[1] or "",
                        "source_document": row[2] or "",
                        "url_document": row[3] or "",
                        "title_document": row[4] or "",
                        "content_document": row[5] or "",
                        "autor_document": row[6] or "",
                    }
                )

            cur.execute(
                sql.SQL(
                    """
                    SELECT
                        uuid,
                        project_id,
                        system_content,
                        user_content,
                        assistant_content,
                        metatags,
                        upvote,
                        downvote
                    FROM {}
                    ORDER BY uuid;
                    """
                ).format(sql.Identifier("public", train_table))
            )
            train_rows = cur.fetchall()

            train_items = []
            for row in train_rows:
                train_items.append(
                    {
                        "uuid": row[0],
                        "project_id": row[1] or "",
                        "system_content": row[2] or "",
                        "user_content": row[3] or "",
                        "assistant_content": row[4] or "",
                        "metatags": row[5] or "",
                        "upvote": row[6] if row[6] is not None else 0,
                        "downvote": row[7] if row[7] is not None else 0,
                    }
                )

    return {
        "project": project,
        "shard_table": shard_table,
        "chunk_table": chunk_table,
        "train_table": train_table,
        "shards": shards,
        "chunks": chunks,
        "train_items": train_items,
    }


def get_project_chat_payload(
    project_slug: str, selected_session_id: str = "", auto_select_latest_session: bool = False
):
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            project = find_project_by_slug(cur, project_slug)
            create_project_tables(cur, project_slug)
            chat_table = f"{project_slug}_chat"
            chat_evaluation_table = f"{project_slug}_chat_evaluation"
            for table_name in [chat_table, chat_evaluation_table]:
                if not table_exists(cur, table_name):
                    raise ValueError(f"La table '{table_name}' est introuvable.")

            cur.execute(
                sql.SQL(
                    """
                    WITH ranked AS (
                        SELECT
                            c.session_id,
                            c.id,
                            c.message,
                            COUNT(*) OVER (PARTITION BY c.session_id)::int AS message_count,
                            ROW_NUMBER() OVER (PARTITION BY c.session_id ORDER BY c.id DESC) AS rn
                        FROM {} AS c
                    )
                    SELECT
                        r.session_id,
                        r.message_count,
                        r.id AS last_message_id,
                        r.message AS last_message_payload,
                        e.rating_global,
                        e.updated_at
                    FROM ranked AS r
                    LEFT JOIN {} AS e
                        ON e.session_id = r.session_id
                    WHERE r.rn = 1
                    ORDER BY r.id DESC;
                    """
                ).format(
                    sql.Identifier("public", chat_table),
                    sql.Identifier("public", chat_evaluation_table),
                )
            )
            session_rows = cur.fetchall()

            sessions = []
            for row in session_rows:
                parsed_last_message = parse_chat_message(row[3])
                sessions.append(
                    {
                        "session_id": row[0],
                        "message_count": int(row[1]),
                        "last_message_id": int(row[2]),
                        "last_message_type": parsed_last_message["type"],
                        "last_message_preview": shorten_text(parsed_last_message["content"], 200),
                        "rating_global": float(row[4]) if row[4] is not None else None,
                        "evaluation_updated_at": row[5],
                    }
                )

            resolved_session_id = (selected_session_id or "").strip()
            if not resolved_session_id and auto_select_latest_session and sessions:
                resolved_session_id = sessions[0]["session_id"]

            selected_session_messages = []
            selected_evaluation = None
            if resolved_session_id:
                cur.execute(
                    sql.SQL(
                        """
                        SELECT
                            id,
                            message
                        FROM {}
                        WHERE session_id = %s
                        ORDER BY id;
                        """
                    ).format(sql.Identifier("public", chat_table)),
                    (resolved_session_id,),
                )
                message_rows = cur.fetchall()
                if not message_rows:
                    raise ValueError(f"Session introuvable: '{resolved_session_id}'.")

                for message_row in message_rows:
                    parsed_message = parse_chat_message(message_row[1])
                    selected_session_messages.append(
                        {
                            "id": int(message_row[0]),
                            "type": parsed_message["type"],
                            "content": parsed_message["content"],
                        }
                    )

                cur.execute(
                    sql.SQL(
                        """
                        SELECT
                            session_id,
                            rating_relevance,
                            rating_accuracy,
                            rating_clarity,
                            rating_completeness,
                            rating_helpfulness,
                            rating_global,
                            comment,
                            created_at,
                            updated_at
                        FROM {}
                        WHERE session_id = %s;
                        """
                    ).format(sql.Identifier("public", chat_evaluation_table)),
                    (resolved_session_id,),
                )
                evaluation_row = cur.fetchone()
                if evaluation_row:
                    selected_evaluation = {
                        "session_id": evaluation_row[0],
                        "rating_relevance": int(evaluation_row[1]),
                        "rating_accuracy": int(evaluation_row[2]),
                        "rating_clarity": int(evaluation_row[3]),
                        "rating_completeness": int(evaluation_row[4]),
                        "rating_helpfulness": int(evaluation_row[5]),
                        "rating_global": float(evaluation_row[6]) if evaluation_row[6] is not None else None,
                        "comment": evaluation_row[7] or "",
                        "created_at": evaluation_row[8],
                        "updated_at": evaluation_row[9],
                    }

    return {
        "project": project,
        "chat_table": chat_table,
        "chat_evaluation_table": chat_evaluation_table,
        "sessions": sessions,
        "selected_session_id": resolved_session_id,
        "selected_session_messages": selected_session_messages,
        "selected_evaluation": selected_evaluation,
    }


def get_project_chat_dashboard_payload(project_slug: str):
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            project = find_project_by_slug(cur, project_slug)
            create_project_tables(cur, project_slug)
            chat_table = f"{project_slug}_chat"
            chat_evaluation_table = f"{project_slug}_chat_evaluation"
            for table_name in [chat_table, chat_evaluation_table]:
                if not table_exists(cur, table_name):
                    raise ValueError(f"La table '{table_name}' est introuvable.")

            cur.execute(
                sql.SQL(
                    """
                    SELECT
                        COUNT(*)::int AS total_sessions,
                        round(avg(rating_global)::numeric, 2) AS avg_global,
                        round(avg(rating_relevance)::numeric, 2) AS avg_relevance,
                        round(avg(rating_accuracy)::numeric, 2) AS avg_accuracy,
                        round(avg(rating_clarity)::numeric, 2) AS avg_clarity,
                        round(avg(rating_completeness)::numeric, 2) AS avg_completeness,
                        round(avg(rating_helpfulness)::numeric, 2) AS avg_helpfulness,
                        round(
                            100.0 * count(*) FILTER (
                                WHERE rating_relevance >= 4
                                  AND rating_accuracy >= 4
                                  AND rating_clarity >= 4
                                  AND rating_completeness >= 4
                                  AND rating_helpfulness >= 4
                            ) / nullif(count(*), 0),
                            2
                        ) AS excellent_rate_pct,
                        round(
                            100.0 * count(*) FILTER (
                                WHERE rating_relevance <= 2
                                   OR rating_accuracy <= 2
                                   OR rating_clarity <= 2
                                   OR rating_completeness <= 2
                                   OR rating_helpfulness <= 2
                            ) / nullif(count(*), 0),
                            2
                        ) AS problematic_rate_pct
                    FROM {};
                    """
                ).format(sql.Identifier("public", chat_evaluation_table))
            )
            global_row = cur.fetchone()

            total_evaluated_sessions = int(global_row[0]) if global_row and global_row[0] is not None else 0
            avg_global_score = to_float_or_none(global_row[1]) if global_row else None

            axis_metrics = [
                {
                    "key": "rating_relevance",
                    "label": CHAT_RATING_LABELS["rating_relevance"],
                    "avg": to_float_or_none(global_row[2]) if global_row else None,
                },
                {
                    "key": "rating_accuracy",
                    "label": CHAT_RATING_LABELS["rating_accuracy"],
                    "avg": to_float_or_none(global_row[3]) if global_row else None,
                },
                {
                    "key": "rating_clarity",
                    "label": CHAT_RATING_LABELS["rating_clarity"],
                    "avg": to_float_or_none(global_row[4]) if global_row else None,
                },
                {
                    "key": "rating_completeness",
                    "label": CHAT_RATING_LABELS["rating_completeness"],
                    "avg": to_float_or_none(global_row[5]) if global_row else None,
                },
                {
                    "key": "rating_helpfulness",
                    "label": CHAT_RATING_LABELS["rating_helpfulness"],
                    "avg": to_float_or_none(global_row[6]) if global_row else None,
                },
            ]
            for axis_metric in axis_metrics:
                axis_metric["avg_pct"] = (
                    round((axis_metric["avg"] / 5.0) * 100.0, 2) if axis_metric["avg"] is not None else None
                )

            excellent_rate_pct = to_float_or_none(global_row[7]) if global_row else None
            problematic_rate_pct = to_float_or_none(global_row[8]) if global_row else None

            non_null_axis_metrics = [metric for metric in axis_metrics if metric["avg"] is not None]
            weakest_axis = min(non_null_axis_metrics, key=lambda metric: metric["avg"]) if non_null_axis_metrics else None

            cur.execute(
                sql.SQL(
                    """
                    WITH session_stats AS (
                        SELECT
                            session_id,
                            COUNT(*)::int AS msg_count
                        FROM {}
                        GROUP BY session_id
                    )
                    SELECT round(avg(s.msg_count)::numeric, 2) AS avg_messages_per_session
                    FROM session_stats s;
                    """
                ).format(
                    sql.Identifier("public", chat_table),
                )
            )
            avg_messages_row = cur.fetchone()
            avg_messages_per_session = to_float_or_none(avg_messages_row[0]) if avg_messages_row else None

            cur.execute(
                sql.SQL(
                    """
                    SELECT
                        date_trunc('week', created_at)::date AS week_start,
                        COUNT(*)::int AS sessions_count,
                        round(avg(rating_global)::numeric, 2) AS avg_global,
                        round(avg(rating_relevance)::numeric, 2) AS avg_relevance,
                        round(avg(rating_accuracy)::numeric, 2) AS avg_accuracy,
                        round(avg(rating_clarity)::numeric, 2) AS avg_clarity,
                        round(avg(rating_completeness)::numeric, 2) AS avg_completeness,
                        round(avg(rating_helpfulness)::numeric, 2) AS avg_helpfulness
                    FROM {}
                    GROUP BY 1
                    ORDER BY 1;
                    """
                ).format(sql.Identifier("public", chat_evaluation_table))
            )
            weekly_rows = cur.fetchall()
            weekly_scores = []
            for weekly_row in weekly_rows:
                avg_week_global = to_float_or_none(weekly_row[2])
                weekly_scores.append(
                    {
                        "week_start": weekly_row[0].isoformat() if weekly_row[0] else "",
                        "sessions_count": int(weekly_row[1]),
                        "avg_global": avg_week_global,
                        "avg_global_pct": round((avg_week_global / 5.0) * 100.0, 2)
                        if avg_week_global is not None
                        else None,
                        "avg_relevance": to_float_or_none(weekly_row[3]),
                        "avg_accuracy": to_float_or_none(weekly_row[4]),
                        "avg_clarity": to_float_or_none(weekly_row[5]),
                        "avg_completeness": to_float_or_none(weekly_row[6]),
                        "avg_helpfulness": to_float_or_none(weekly_row[7]),
                    }
                )

            cur.execute(
                sql.SQL(
                    """
                    WITH session_stats AS (
                        SELECT
                            session_id,
                            COUNT(*)::int AS msg_count
                        FROM {}
                        GROUP BY session_id
                    )
                    SELECT
                        s.msg_count,
                        COUNT(*)::int AS sessions_count,
                        round(avg(e.rating_global)::numeric, 2) AS avg_global
                    FROM session_stats s
                    JOIN {} e
                      ON e.session_id = s.session_id
                    GROUP BY s.msg_count
                    ORDER BY s.msg_count;
                    """
                ).format(
                    sql.Identifier("public", chat_table),
                    sql.Identifier("public", chat_evaluation_table),
                )
            )
            length_rows = cur.fetchall()
            length_score_relation = []
            for length_row in length_rows:
                avg_length_global = to_float_or_none(length_row[2])
                length_score_relation.append(
                    {
                        "msg_count": int(length_row[0]),
                        "sessions_count": int(length_row[1]),
                        "avg_global": avg_length_global,
                        "avg_global_pct": round((avg_length_global / 5.0) * 100.0, 2)
                        if avg_length_global is not None
                        else None,
                    }
                )

            cur.execute(
                sql.SQL(
                    """
                    WITH session_stats AS (
                        SELECT
                            session_id,
                            COUNT(*)::int AS msg_count
                        FROM {}
                        GROUP BY session_id
                    )
                    SELECT
                        CASE
                            WHEN s.msg_count BETWEEN 1 AND 2 THEN '1-2 messages'
                            WHEN s.msg_count BETWEEN 3 AND 5 THEN '3-5 messages'
                            WHEN s.msg_count BETWEEN 6 AND 10 THEN '6-10 messages'
                            ELSE '11+ messages'
                        END AS bucket_label,
                        CASE
                            WHEN s.msg_count BETWEEN 1 AND 2 THEN 1
                            WHEN s.msg_count BETWEEN 3 AND 5 THEN 2
                            WHEN s.msg_count BETWEEN 6 AND 10 THEN 3
                            ELSE 4
                        END AS bucket_order,
                        COUNT(*)::int AS sessions_count,
                        round(avg(e.rating_global)::numeric, 2) AS avg_global
                    FROM session_stats s
                    JOIN {} e
                      ON e.session_id = s.session_id
                    GROUP BY 1, 2
                    ORDER BY 2;
                    """
                ).format(
                    sql.Identifier("public", chat_table),
                    sql.Identifier("public", chat_evaluation_table),
                )
            )
            bucket_rows = cur.fetchall()
            length_buckets = []
            for bucket_row in bucket_rows:
                avg_bucket_global = to_float_or_none(bucket_row[3])
                length_buckets.append(
                    {
                        "bucket_label": bucket_row[0],
                        "bucket_order": int(bucket_row[1]),
                        "sessions_count": int(bucket_row[2]),
                        "avg_global": avg_bucket_global,
                        "avg_global_pct": round((avg_bucket_global / 5.0) * 100.0, 2)
                        if avg_bucket_global is not None
                        else None,
                    }
                )

            cur.execute(
                sql.SQL(
                    """
                    WITH session_stats AS (
                        SELECT
                            session_id,
                            COUNT(*)::int AS msg_count
                        FROM {}
                        GROUP BY session_id
                    )
                    SELECT corr(s.msg_count::float, e.rating_global::float) AS corr_msg_count_rating_global
                    FROM session_stats s
                    JOIN {} e
                      ON e.session_id = s.session_id;
                    """
                ).format(
                    sql.Identifier("public", chat_table),
                    sql.Identifier("public", chat_evaluation_table),
                )
            )
            correlation_row = cur.fetchone()
            corr_msg_count_rating_global = to_float_or_none(correlation_row[0]) if correlation_row else None

    return {
        "project": project,
        "chat_table": chat_table,
        "chat_evaluation_table": chat_evaluation_table,
        "total_evaluated_sessions": total_evaluated_sessions,
        "avg_global_score": avg_global_score,
        "axis_metrics": axis_metrics,
        "excellent_rate_pct": excellent_rate_pct,
        "problematic_rate_pct": problematic_rate_pct,
        "weakest_axis": weakest_axis,
        "avg_messages_per_session": avg_messages_per_session,
        "weekly_scores": weekly_scores,
        "length_score_relation": length_score_relation,
        "length_buckets": length_buckets,
        "corr_msg_count_rating_global": corr_msg_count_rating_global,
    }


def upsert_chat_evaluation(project_slug: str, payload):
    session_id = (payload.get("session_id") or "").strip()
    if not session_id:
        raise ValueError("Le champ 'session_id' est obligatoire.")

    ratings = {}
    for rating_field in CHAT_RATING_FIELDS:
        ratings[rating_field] = parse_rating_field(payload.get(rating_field), rating_field)
    comment = (payload.get("comment") or "").strip()

    with get_db_connection() as conn:
        with conn.cursor() as cur:
            _ = find_project_by_slug(cur, project_slug)
            create_project_tables(cur, project_slug)
            chat_table = f"{project_slug}_chat"
            chat_evaluation_table = f"{project_slug}_chat_evaluation"
            for table_name in [chat_table, chat_evaluation_table]:
                if not table_exists(cur, table_name):
                    raise ValueError(f"La table '{table_name}' est introuvable.")

            cur.execute(
                sql.SQL("SELECT 1 FROM {} WHERE session_id = %s LIMIT 1;").format(
                    sql.Identifier("public", chat_table)
                ),
                (session_id,),
            )
            if not cur.fetchone():
                raise ValueError(f"Session introuvable pour ce projet: '{session_id}'.")

            cur.execute(
                sql.SQL(
                    """
                    INSERT INTO {} (
                        session_id,
                        rating_relevance,
                        rating_accuracy,
                        rating_clarity,
                        rating_completeness,
                        rating_helpfulness,
                        comment,
                        updated_at
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s, now())
                    ON CONFLICT (session_id)
                    DO UPDATE SET
                        rating_relevance = EXCLUDED.rating_relevance,
                        rating_accuracy = EXCLUDED.rating_accuracy,
                        rating_clarity = EXCLUDED.rating_clarity,
                        rating_completeness = EXCLUDED.rating_completeness,
                        rating_helpfulness = EXCLUDED.rating_helpfulness,
                        comment = EXCLUDED.comment,
                        updated_at = now();
                    """
                ).format(sql.Identifier("public", chat_evaluation_table)),
                (
                    session_id,
                    ratings["rating_relevance"],
                    ratings["rating_accuracy"],
                    ratings["rating_clarity"],
                    ratings["rating_completeness"],
                    ratings["rating_helpfulness"],
                    comment or None,
                ),
            )

    return session_id


def delete_project(project_slug: str):
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            _ = find_project_by_slug(cur, project_slug)
            for table_name in [
                f"{project_slug}_chat_evaluation",
                f"{project_slug}_chat",
                f"{project_slug}_chunk",
                f"{project_slug}_train",
                f"{project_slug}_shard",
            ]:
                cur.execute(
                    sql.SQL("DROP TABLE IF EXISTS {} CASCADE;").format(
                        sql.Identifier("public", table_name)
                    )
                )
            cur.execute(
                sql.SQL("DELETE FROM public.{} WHERE project_nameslug = %s;").format(
                    sql.Identifier(PROJECTS_TABLE)
                ),
                (project_slug,),
            )


def add_shard_record(project_slug: str, payload):
    source_document = (payload.get("source_document") or "").strip()
    url_document = (payload.get("url_document") or "").strip()
    title_document = (payload.get("title_document") or "").strip()
    content_document = (payload.get("content_document") or "").strip()
    autor_document = (payload.get("autor_document") or "").strip()
    if not content_document:
        raise ValueError("Le champ 'content_document' est obligatoire pour un shard.")

    shard_uuid = str(uuid4())
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            project = find_project_by_slug(cur, project_slug)
            shard_table = f"{project_slug}_shard"
            if not table_exists(cur, shard_table):
                raise ValueError(f"La table '{shard_table}' est introuvable.")
            cur.execute(
                sql.SQL(
                    """
                    INSERT INTO {} (
                        uuid,
                        project_id,
                        source_document,
                        url_document,
                        title_document,
                        content_document,
                        autor_document
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s);
                    """
                ).format(sql.Identifier("public", shard_table)),
                (
                    shard_uuid,
                    project["uuid"],
                    source_document or None,
                    url_document or None,
                    title_document or None,
                    content_document,
                    autor_document or None,
                ),
            )
    return shard_uuid


def delete_shard_record(project_slug: str, shard_uuid: str):
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            _ = find_project_by_slug(cur, project_slug)
            shard_table = f"{project_slug}_shard"
            chunk_table = f"{project_slug}_chunk"
            cur.execute(
                sql.SQL("DELETE FROM {} WHERE shard_id = %s;").format(
                    sql.Identifier("public", chunk_table)
                ),
                (shard_uuid,),
            )
            cur.execute(
                sql.SQL("DELETE FROM {} WHERE uuid = %s;").format(
                    sql.Identifier("public", shard_table)
                ),
                (shard_uuid,),
            )


def add_chunk_record(project_slug: str, payload):
    shard_id = (payload.get("shard_id") or "").strip()
    source_document = (payload.get("source_document") or "").strip()
    url_document = (payload.get("url_document") or "").strip()
    title_document = (payload.get("title_document") or "").strip()
    content_document = (payload.get("content_document") or "").strip()
    autor_document = (payload.get("autor_document") or "").strip()

    if not shard_id:
        raise ValueError("Le champ 'shard_id' est obligatoire pour un chunk.")
    if not content_document:
        raise ValueError("Le champ 'content_document' est obligatoire pour un chunk.")

    chunk_uuid = str(uuid4())
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            _ = find_project_by_slug(cur, project_slug)
            shard_table = f"{project_slug}_shard"
            chunk_table = f"{project_slug}_chunk"
            cur.execute(
                sql.SQL("SELECT 1 FROM {} WHERE uuid = %s;").format(
                    sql.Identifier("public", shard_table)
                ),
                (shard_id,),
            )
            if not cur.fetchone():
                raise ValueError(f"Shard '{shard_id}' introuvable pour ce projet.")
            cur.execute(
                sql.SQL(
                    """
                    INSERT INTO {} (
                        uuid,
                        shard_id,
                        source_document,
                        url_document,
                        title_document,
                        content_document,
                        autor_document
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s);
                    """
                ).format(sql.Identifier("public", chunk_table)),
                (
                    chunk_uuid,
                    shard_id,
                    source_document or None,
                    url_document or None,
                    title_document or None,
                    content_document,
                    autor_document or None,
                ),
            )
    return chunk_uuid


def delete_chunk_record(project_slug: str, chunk_uuid: str):
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            _ = find_project_by_slug(cur, project_slug)
            chunk_table = f"{project_slug}_chunk"
            cur.execute(
                sql.SQL("DELETE FROM {} WHERE uuid = %s;").format(
                    sql.Identifier("public", chunk_table)
                ),
                (chunk_uuid,),
            )


def delete_train_record(project_slug: str, train_uuid: str):
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            _ = find_project_by_slug(cur, project_slug)
            train_table = f"{project_slug}_train"
            cur.execute(
                sql.SQL("DELETE FROM {} WHERE uuid = %s;").format(
                    sql.Identifier("public", train_table)
                ),
                (train_uuid,),
            )


def vote_train_record(project_slug: str, train_uuid: str, direction: str):
    if direction not in {"up", "down"}:
        raise ValueError("Direction de vote invalide.")

    with get_db_connection() as conn:
        with conn.cursor() as cur:
            _ = find_project_by_slug(cur, project_slug)
            train_table = f"{project_slug}_train"
            field = "upvote" if direction == "up" else "downvote"
            cur.execute(
                sql.SQL("UPDATE {} SET {} = COALESCE({}, 0) + 1 WHERE uuid = %s;").format(
                    sql.Identifier("public", train_table),
                    sql.Identifier(field),
                    sql.Identifier(field),
                ),
                (train_uuid,),
            )
            if cur.rowcount == 0:
                raise ValueError(f"Item train '{train_uuid}' introuvable.")


def add_train_record(project_slug: str, payload):
    system_content = (payload.get("system_content") or "").strip()
    user_content = (payload.get("user_content") or "").strip()
    assistant_content = (payload.get("assistant_content") or "").strip()
    metatags = normalize_metatags(payload.get("metatags"))
    upvote = parse_int_field(payload.get("upvote"), "upvote", default=0)
    downvote = parse_int_field(payload.get("downvote"), "downvote", default=0)

    if not any([system_content, user_content, assistant_content]):
        raise ValueError("Saisissez au moins un contenu: system, user ou assistant.")
    if upvote < 0 or downvote < 0:
        raise ValueError("Les valeurs upvote/downvote doivent etre positives.")

    train_uuid = str(uuid4())

    with get_db_connection() as conn:
        with conn.cursor() as cur:
            project = find_project_by_slug(cur, project_slug)
            train_table = f"{project_slug}_train"
            if not table_exists(cur, train_table):
                raise ValueError(f"La table '{train_table}' est introuvable.")
            ensure_train_table_schema(cur, train_table)

            cur.execute(
                sql.SQL(
                    """
                    INSERT INTO {} (
                        uuid,
                        project_id,
                        system_content,
                        user_content,
                        assistant_content,
                        metatags,
                        upvote,
                        downvote
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s);
                    """
                ).format(sql.Identifier("public", train_table)),
                (
                    train_uuid,
                    project["uuid"],
                    system_content or None,
                    user_content or None,
                    assistant_content or None,
                    metatags or None,
                    upvote,
                    downvote,
                ),
            )

    return train_uuid


def estimate_tokens(text: str, options) -> int:
    if not text:
        return 0
    if options["tokenEstimator"] == "chars":
        return max(1, (len(text) + options["charsPerToken"] - 1) // options["charsPerToken"])
    return len(re.findall(r"\S+", text))


def split_by_token_window(text: str, max_tokens: int, overlap_tokens: int, options):
    if not text.strip():
        return []

    if options["tokenEstimator"] == "chars":
        window_chars = max(1, max_tokens * options["charsPerToken"])
        overlap_chars = max(0, overlap_tokens * options["charsPerToken"])
        if overlap_chars >= window_chars:
            overlap_chars = window_chars - 1
        step = max(1, window_chars - overlap_chars)

        chunks = []
        start = 0
        while start < len(text):
            part = text[start : start + window_chars].strip()
            if part:
                chunks.append(part)
            if start + window_chars >= len(text):
                break
            start += step
        return chunks

    words = re.findall(r"\S+", text)
    if not words:
        return []

    if overlap_tokens >= max_tokens:
        overlap_tokens = max_tokens - 1
    step = max(1, max_tokens - overlap_tokens)

    chunks = []
    start = 0
    while start < len(words):
        part_words = words[start : start + max_tokens]
        if part_words:
            chunks.append(" ".join(part_words))
        if start + max_tokens >= len(words):
            break
        start += step
    return chunks


def split_markdown_sections(markdown_text: str, heading_max_level: int):
    text = (markdown_text or "").replace("\r\n", "\n")
    if not text.strip():
        return []

    sections = []
    heading_stack = []
    current_title = "Introduction"
    current_path = ["Introduction"]
    current_lines = []

    def push_current_section():
        content = "\n".join(current_lines).strip()
        if content or current_title != "Introduction":
            sections.append(
                {
                    "section_title": current_title,
                    "section_path": " > ".join(current_path),
                    "content": content,
                }
            )

    for line in text.split("\n"):
        heading_match = re.match(r"^(#{1,6})\s+(.*)$", line.strip())
        if heading_match:
            level = len(heading_match.group(1))
            title = heading_match.group(2).strip() or "Section"
            if level <= heading_max_level:
                push_current_section()
                heading_stack = heading_stack[: level - 1]
                heading_stack.append(title)
                current_title = title
                current_path = heading_stack.copy()
                current_lines = []
                continue
        current_lines.append(line)

    push_current_section()

    normalized = []
    for section in sections:
        section_content = section["content"].strip()
        if section_content:
            normalized.append(section)
        elif section["section_title"]:
            normalized.append(
                {
                    "section_title": section["section_title"],
                    "section_path": section["section_path"],
                    "content": section["section_title"],
                }
            )
    return normalized


def split_section_content(section_content: str, options):
    section_content = (section_content or "").strip()
    if not section_content:
        return []

    if estimate_tokens(section_content, options) <= options["chunkMaxTokens"]:
        return [section_content]

    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", section_content) if p.strip()]
    if not paragraphs:
        paragraphs = [section_content]

    hard_limited_parts = []
    for paragraph in paragraphs:
        if estimate_tokens(paragraph, options) <= options["chunkMaxTokens"]:
            hard_limited_parts.append(paragraph)
        else:
            hard_limited_parts.extend(
                split_by_token_window(
                    paragraph,
                    options["chunkMaxTokens"],
                    options["chunkOverlapTokens"],
                    options,
                )
            )

    chunks = []
    current_parts = []
    for part in hard_limited_parts:
        candidate_parts = current_parts + [part]
        candidate_text = "\n\n".join(candidate_parts).strip()
        if not current_parts or estimate_tokens(candidate_text, options) <= options["chunkMaxTokens"]:
            current_parts.append(part)
            continue

        chunks.append("\n\n".join(current_parts).strip())
        overlap_seed = split_by_token_window(
            chunks[-1],
            options["chunkOverlapTokens"],
            0,
            options,
        )
        overlap_text = overlap_seed[-1].strip() if overlap_seed else ""
        current_parts = [part]
        if overlap_text:
            with_overlap = f"{overlap_text}\n\n{part}".strip()
            if estimate_tokens(with_overlap, options) <= options["hardMaxTokens"]:
                current_parts = [overlap_text, part]

    if current_parts:
        chunks.append("\n\n".join(current_parts).strip())

    return [chunk for chunk in chunks if chunk]


def build_chunks_for_document(document, previous_document_id, options):
    sections = split_markdown_sections(
        document.get("content_document", ""),
        options["headingMaxLevel"],
    )
    if not sections:
        sections = [
            {
                "section_title": document.get("title_document") or "Document",
                "section_path": document.get("title_document") or "Document",
                "content": document.get("content_document") or "",
            }
        ]

    items = []
    for section in sections:
        section_parts = split_section_content(section["content"], options)
        if not section_parts:
            section_parts = [section["section_title"]]

        for section_part in section_parts:
            chunk_id = str(uuid4())
            text = section_part.strip()
            if not text:
                text = section["section_title"]
            if (
                section["section_title"]
                and section["section_title"] != "Introduction"
                and not text.startswith(section["section_title"])
            ):
                text = f"{section['section_title']}\n\n{text}"
            items.append(
                {
                    "chunk_id": chunk_id,
                    "pageContent": text,
                    "text": text,
                    "metadata": {
                        "document_id": document["uuid"],
                        "section_title": section["section_title"],
                        "section_path": section["section_path"],
                        "previous_document_id": previous_document_id,
                        "previous_chunk_id": None,
                        "next_chunk_id": None,
                    },
                }
            )

    for index, item in enumerate(items):
        if index > 0:
            item["metadata"]["previous_chunk_id"] = items[index - 1]["chunk_id"]
        if index < len(items) - 1:
            item["metadata"]["next_chunk_id"] = items[index + 1]["chunk_id"]

    return items


def chunkify_project_shards(project_slug: str, options):
    shard_table = f"{project_slug}_shard"
    chunk_table = f"{project_slug}_chunk"
    generated_items = []

    with get_db_connection() as conn:
        with conn.cursor() as cur:
            if not table_exists(cur, shard_table):
                raise ValueError(f"La table '{shard_table}' est introuvable.")
            if not table_exists(cur, chunk_table):
                raise ValueError(f"La table '{chunk_table}' est introuvable.")

            cur.execute(
                sql.SQL(
                    """
                    SELECT
                        uuid,
                        project_id,
                        source_document,
                        url_document,
                        title_document,
                        content_document,
                        autor_document
                    FROM {}
                    ORDER BY uuid;
                    """
                ).format(sql.Identifier("public", shard_table))
            )
            shard_rows = cur.fetchall()

            previous_document_id = None
            for shard_row in shard_rows:
                document = {
                    "uuid": shard_row[0],
                    "project_id": shard_row[1],
                    "source_document": shard_row[2],
                    "url_document": shard_row[3],
                    "title_document": shard_row[4],
                    "content_document": shard_row[5] or "",
                    "autor_document": shard_row[6],
                }
                document_chunks = build_chunks_for_document(
                    document,
                    previous_document_id,
                    options,
                )
                previous_document_id = document["uuid"]

                cur.execute(
                    sql.SQL("DELETE FROM {} WHERE shard_id = %s;").format(
                        sql.Identifier("public", chunk_table)
                    ),
                    (document["uuid"],),
                )

                for chunk_item in document_chunks:
                    generated_items.append(chunk_item)
                    cur.execute(
                        sql.SQL(
                            """
                            INSERT INTO {} (
                                uuid,
                                shard_id,
                                source_document,
                                url_document,
                                title_document,
                                content_document,
                                autor_document
                            ) VALUES (%s, %s, %s, %s, %s, %s, %s);
                            """
                        ).format(sql.Identifier("public", chunk_table)),
                        (
                            chunk_item["chunk_id"],
                            document["uuid"],
                            document["source_document"],
                            document["url_document"],
                            chunk_item["metadata"]["section_title"],
                            chunk_item["pageContent"],
                            document["autor_document"],
                        ),
                    )

    return generated_items


def list_projects_shards():
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            ensure_projects_table(cur)
            cur.execute(
                sql.SQL(
                    """
                    SELECT uuid, project_name, project_nameslug
                    FROM public.{}
                    ORDER BY uuid DESC;
                    """
                ).format(sql.Identifier(PROJECTS_TABLE))
            )
            project_rows = cur.fetchall()

            projects = []
            for project_row in project_rows:
                project_uuid, project_name, project_slug = project_row
                shard_table = f"{project_slug}_shard"
                chunk_table = f"{project_slug}_chunk"
                train_table = f"{project_slug}_train"
                chat_table = f"{project_slug}_chat"
                chat_evaluation_table = f"{project_slug}_chat_evaluation"

                if not table_exists(cur, shard_table):
                    shard_rows = []
                elif table_exists(cur, chunk_table):
                    cur.execute(
                        sql.SQL(
                            """
                            SELECT
                                s.uuid,
                                s.title_document,
                                s.source_document,
                                COUNT(c.uuid)::int AS chunk_count
                            FROM {} AS s
                            LEFT JOIN {} AS c
                                ON c.shard_id = s.uuid
                            GROUP BY s.uuid, s.title_document, s.source_document
                            ORDER BY s.uuid;
                            """
                        ).format(
                            sql.Identifier("public", shard_table),
                            sql.Identifier("public", chunk_table),
                        )
                    )
                    shard_rows = cur.fetchall()
                else:
                    cur.execute(
                        sql.SQL(
                            """
                            SELECT
                                s.uuid,
                                s.title_document,
                                s.source_document,
                                0 AS chunk_count
                            FROM {} AS s
                            ORDER BY s.uuid;
                            """
                        ).format(sql.Identifier("public", shard_table))
                    )
                    shard_rows = cur.fetchall()

                shards = []
                total_chunks = 0
                for shard_row in shard_rows:
                    chunk_count = int(shard_row[3])
                    total_chunks += chunk_count
                    shards.append(
                        {
                            "uuid": shard_row[0],
                            "title_document": shard_row[1],
                            "source_document": shard_row[2],
                            "chunk_count": chunk_count,
                        }
                    )

                train_count = 0
                train_items = []
                if table_exists(cur, train_table):
                    ensure_train_table_schema(cur, train_table)
                    cur.execute(
                        sql.SQL(
                            """
                            SELECT COUNT(*)::int
                            FROM {};
                            """
                        ).format(sql.Identifier("public", train_table))
                    )
                    train_count = int(cur.fetchone()[0])
                    cur.execute(
                        sql.SQL(
                            """
                            SELECT
                                uuid,
                                system_content,
                                user_content,
                                assistant_content,
                                metatags,
                                upvote,
                                downvote
                            FROM {}
                            ORDER BY last_date_edit DESC, uuid DESC
                            LIMIT 5;
                            """
                        ).format(sql.Identifier("public", train_table))
                    )
                    train_rows = cur.fetchall()
                    for train_row in train_rows:
                        train_items.append(
                            {
                                "uuid": train_row[0],
                                "system_content": train_row[1] or "",
                                "user_content": train_row[2] or "",
                                "assistant_content": train_row[3] or "",
                                "metatags": train_row[4] or "",
                                "upvote": train_row[5] if train_row[5] is not None else 0,
                                "downvote": train_row[6] if train_row[6] is not None else 0,
                            }
                        )

                chat_message_count = 0
                chat_session_count = 0
                if table_exists(cur, chat_table):
                    cur.execute(
                        sql.SQL(
                            """
                            SELECT
                                COUNT(*)::int AS message_count,
                                COUNT(DISTINCT session_id)::int AS session_count
                            FROM {};
                            """
                        ).format(sql.Identifier("public", chat_table))
                    )
                    chat_stats_row = cur.fetchone()
                    chat_message_count = int(chat_stats_row[0]) if chat_stats_row else 0
                    chat_session_count = int(chat_stats_row[1]) if chat_stats_row else 0

                chat_evaluation_count = 0
                if table_exists(cur, chat_evaluation_table):
                    cur.execute(
                        sql.SQL(
                            """
                            SELECT COUNT(*)::int
                            FROM {};
                            """
                        ).format(sql.Identifier("public", chat_evaluation_table))
                    )
                    chat_evaluation_count = int(cur.fetchone()[0])

                projects.append(
                    {
                        "uuid": project_uuid,
                        "name": project_name,
                        "slug": project_slug,
                        "shard_table": shard_table,
                        "chunk_table": chunk_table,
                        "train_table": train_table,
                        "chat_table": chat_table,
                        "chat_evaluation_table": chat_evaluation_table,
                        "shard_count": len(shards),
                        "total_chunks": total_chunks,
                        "train_count": train_count,
                        "chat_message_count": chat_message_count,
                        "chat_session_count": chat_session_count,
                        "chat_evaluation_count": chat_evaluation_count,
                        "train_items": train_items,
                        "shards": shards,
                    }
                )

    return projects


def resolve_return_url(return_to: str, default_endpoint: str, project_slug: str):
    allowed_no_args = {"home", "projects_shards", "projects_train", "projects_tree"}
    allowed_with_slug = {
        "project_shard_list",
        "project_shard_new",
        "project_train_list",
        "project_train_new",
        "project_chunk_list",
        "project_chunk_new",
        "project_chat_list",
        "project_chat_dashboard",
    }

    endpoint = return_to if return_to in (allowed_no_args | allowed_with_slug) else default_endpoint
    if endpoint in allowed_with_slug:
        return url_for(endpoint, project_slug=project_slug)
    return url_for(endpoint)


@app.get("/")
def home():
    try:
        projects = list_projects()
        db_error = None
    except Exception as exc:
        projects = []
        db_error = str(exc)
    return render_template("index.html", projects=projects, db_error=db_error)


@app.post("/projects")
def add_project():
    project_name = request.form.get("project_name", "")
    try:
        project_uuid, slug = create_project(project_name)
        flash(
            f"Projet cree avec succes. UUID: {project_uuid} | slug: {slug}",
            "success",
        )
    except ValueError as exc:
        flash(str(exc), "error")
    except Exception as exc:
        flash(f"Erreur PostgreSQL: {exc}", "error")
    return redirect(url_for("home"))


@app.post("/projects/<project_slug>/delete")
def remove_project(project_slug):
    try:
        delete_project(project_slug)
        flash(f"Projet '{project_slug}' supprime.", "success")
    except Exception as exc:
        flash(f"Erreur suppression projet: {exc}", "error")
    return redirect(url_for("home"))


@app.get("/projects/<project_slug>/shards/new")
def project_shard_new(project_slug):
    try:
        payload = get_project_crud_payload(project_slug)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("shard_form.html", payload=payload, db_error=db_error)


@app.get("/projects/<project_slug>/shards/<shard_uuid>")
def project_shard_view(project_slug, shard_uuid):
    try:
        payload = get_project_crud_payload(project_slug)
        shard = next((item for item in payload["shards"] if item["uuid"] == shard_uuid), None)
        if shard is None:
            raise ValueError(f"Shard introuvable pour l'UUID: {shard_uuid}")
        db_error = None
    except Exception as exc:
        payload = None
        shard = None
        db_error = str(exc)
    return render_template("shard_view.html", payload=payload, shard=shard, db_error=db_error)


@app.get("/projects/<project_slug>/shard-list")
def project_shard_list(project_slug):
    try:
        payload = get_project_crud_payload(project_slug)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("shard_list.html", payload=payload, db_error=db_error)


@app.post("/projects/<project_slug>/shards/add")
def add_shard_item(project_slug):
    try:
        shard_uuid = add_shard_record(project_slug, request.form.to_dict())
        flash(f"Shard ajoute pour '{project_slug}'. UUID: {shard_uuid}", "success")
    except Exception as exc:
        flash(f"Erreur ajout shard: {exc}", "error")
    return_to = request.form.get("return_to", "project_shard_list")
    return redirect(resolve_return_url(return_to, "project_shard_list", project_slug))


@app.post("/projects/<project_slug>/shards/<shard_uuid>/delete")
def remove_shard_item(project_slug, shard_uuid):
    try:
        delete_shard_record(project_slug, shard_uuid)
        flash(f"Shard supprime: {shard_uuid}", "success")
    except Exception as exc:
        flash(f"Erreur suppression shard: {exc}", "error")
    return redirect(url_for("project_shard_list", project_slug=project_slug))


@app.get("/projects/<project_slug>/train-list")
def project_train_list(project_slug):
    try:
        payload = get_project_crud_payload(project_slug)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("train_list.html", payload=payload, db_error=db_error)


@app.get("/projects/<project_slug>/trains/new")
def project_train_new(project_slug):
    try:
        payload = get_project_crud_payload(project_slug)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("train_form.html", payload=payload, db_error=db_error)


@app.post("/projects/<project_slug>/trains/<train_uuid>/delete")
def remove_train_item(project_slug, train_uuid):
    try:
        delete_train_record(project_slug, train_uuid)
        flash(f"Item train supprime: {train_uuid}", "success")
    except Exception as exc:
        flash(f"Erreur suppression train: {exc}", "error")
    return redirect(url_for("project_train_list", project_slug=project_slug))


@app.post("/projects/<project_slug>/trains/<train_uuid>/vote")
def vote_train_item(project_slug, train_uuid):
    direction = (request.form.get("direction") or "").strip().lower()
    try:
        vote_train_record(project_slug, train_uuid, direction)
        flash(f"Vote enregistre pour l'item train {train_uuid}.", "success")
    except Exception as exc:
        flash(f"Erreur vote train: {exc}", "error")
    return redirect(url_for("project_train_list", project_slug=project_slug))


@app.get("/projects/<project_slug>/chunk-list")
def project_chunk_list(project_slug):
    try:
        payload = get_project_crud_payload(project_slug)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("chunk_list.html", payload=payload, db_error=db_error)


@app.get("/projects/<project_slug>/chunks/new")
def project_chunk_new(project_slug):
    selected_shard_id = (request.args.get("shard_id") or "").strip()
    try:
        payload = get_project_crud_payload(project_slug)
        shard_ids = {item["uuid"] for item in payload["shards"]}
        if selected_shard_id and selected_shard_id not in shard_ids:
            selected_shard_id = ""
        db_error = None
    except Exception as exc:
        payload = None
        selected_shard_id = ""
        db_error = str(exc)
    return render_template(
        "chunk_form.html",
        payload=payload,
        selected_shard_id=selected_shard_id,
        db_error=db_error,
    )


@app.get("/projects/<project_slug>/chunks/<chunk_uuid>")
def project_chunk_view(project_slug, chunk_uuid):
    try:
        payload = get_project_crud_payload(project_slug)
        chunk = next((item for item in payload["chunks"] if item["uuid"] == chunk_uuid), None)
        if chunk is None:
            raise ValueError(f"Chunk introuvable pour l'UUID: {chunk_uuid}")
        db_error = None
    except Exception as exc:
        payload = None
        chunk = None
        db_error = str(exc)
    return render_template("chunk_view.html", payload=payload, chunk=chunk, db_error=db_error)


@app.post("/projects/<project_slug>/chunks/add")
def add_chunk_item(project_slug):
    try:
        chunk_uuid = add_chunk_record(project_slug, request.form.to_dict())
        flash(f"Chunk ajoute pour '{project_slug}'. UUID: {chunk_uuid}", "success")
    except Exception as exc:
        flash(f"Erreur ajout chunk: {exc}", "error")
    return_to = request.form.get("return_to", "project_chunk_list")
    return redirect(resolve_return_url(return_to, "project_chunk_list", project_slug))


@app.post("/projects/<project_slug>/chunks/<chunk_uuid>/delete")
def remove_chunk_item(project_slug, chunk_uuid):
    try:
        delete_chunk_record(project_slug, chunk_uuid)
        flash(f"Chunk supprime: {chunk_uuid}", "success")
    except Exception as exc:
        flash(f"Erreur suppression chunk: {exc}", "error")
    return redirect(url_for("project_chunk_list", project_slug=project_slug))


@app.get("/projects/<project_slug>/chat-list")
def project_chat_list(project_slug):
    try:
        payload = get_project_chat_payload(project_slug)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("chat_list.html", payload=payload, db_error=db_error)


@app.get("/projects/<project_slug>/chat-sessions/<session_id>")
def project_chat_session(project_slug, session_id):
    selected_session_id = (session_id or "").strip()
    try:
        payload = get_project_chat_payload(project_slug, selected_session_id)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("chat_session.html", payload=payload, db_error=db_error)


@app.get("/projects/<project_slug>/chat-dashboard")
def project_chat_dashboard(project_slug):
    try:
        payload = get_project_chat_dashboard_payload(project_slug)
        db_error = None
    except Exception as exc:
        payload = None
        db_error = str(exc)
    return render_template("chat_dashboard.html", payload=payload, db_error=db_error)


@app.post("/projects/<project_slug>/chat-evaluations")
def submit_chat_evaluation(project_slug):
    form_payload = request.form.to_dict()
    session_id = (form_payload.get("session_id") or "").strip()
    try:
        session_id = upsert_chat_evaluation(project_slug, form_payload)
        flash(f"Evaluation enregistree pour la session '{session_id}'.", "success")
    except ValueError as exc:
        flash(str(exc), "error")
    except Exception as exc:
        flash(f"Erreur evaluation conversation: {exc}", "error")

    if session_id:
        return redirect(url_for("project_chat_session", project_slug=project_slug, session_id=session_id))
    return redirect(url_for("project_chat_list", project_slug=project_slug))


@app.get("/projects/shards")
def projects_shards():
    try:
        projects = list_projects_shards()
        db_error = None
    except Exception as exc:
        projects = []
        db_error = str(exc)
    return render_template("project_shards.html", projects=projects, db_error=db_error)


@app.get("/projects/train")
def projects_train():
    try:
        projects = list_projects_shards()
        db_error = None
    except Exception as exc:
        projects = []
        db_error = str(exc)
    return render_template("project_train.html", projects=projects, db_error=db_error)


@app.get("/projects/tree")
def projects_tree():
    try:
        projects = list_projects_shards()
        db_error = None
    except Exception as exc:
        projects = []
        db_error = str(exc)
    return render_template("project_tree.html", projects=projects, db_error=db_error)


@app.post("/projects/<project_slug>/chunkify")
def chunkify_project(project_slug):
    incoming_payload = request.get_json(silent=True)
    if incoming_payload is None:
        incoming_payload = request.form.to_dict()
    options = parse_chunk_options(incoming_payload)

    try:
        generated_items = chunkify_project_shards(project_slug, options)
        if request.is_json:
            return {
                "project_slug": project_slug,
                "generated_chunks": len(generated_items),
                "items": generated_items,
                "options": options,
            }
        flash(
            f"Chunking termine pour '{project_slug}': {len(generated_items)} chunk(s) genere(s).",
            "success",
        )
    except Exception as exc:
        if request.is_json:
            return {"error": str(exc)}, 400
        flash(f"Erreur chunking: {exc}", "error")
    return_to = request.form.get("return_to", "project_shard_list")
    return redirect(resolve_return_url(return_to, "project_shard_list", project_slug))


@app.post("/projects/<project_slug>/train")
def add_train_item(project_slug):
    payload = request.form.to_dict()
    try:
        train_uuid = add_train_record(project_slug, payload)
        flash(
            f"Exemple train ajoute pour '{project_slug}'. UUID: {train_uuid}",
            "success",
        )
    except ValueError as exc:
        flash(str(exc), "error")
    except Exception as exc:
        flash(f"Erreur train: {exc}", "error")
    return_to = request.form.get("return_to", "project_train_list")
    return redirect(resolve_return_url(return_to, "project_train_list", project_slug))


@app.get("/health")
def health():
    return {"status": "ok"}


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=True)
