CREATE TABLE "public"."exempleprojec_chunk" (
    "uuid" text NOT NULL,
    "shard_id" text,
    "source_document" text,
    "url_document" text,
    "title_document" text,
    "content_document" text,
    "autor_document" text,
    "last_date_edit" text DEFAULT now()::text NOT NULL
)
WITH (oids = false);

CREATE TABLE "public"."exempleproject_shard" (
    "uuid" text NOT NULL,
    "project_id" text,
    "source_document" text,
    "url_document" text,
    "title_document" text,
    "content_document" text,
    "autor_document" text,
    "last_date_edit" text DEFAULT now()::text NOT NULL
)
WITH (oids = false);

CREATE TABLE "public"."exempleproject_train" (
    "uuid" text NOT NULL,
    "project_id" text,
    "system_content" text,
    "user_content" text,
    "assistant_content" text,
    "metatags" text,
    "upvote" integer DEFAULT 0 ,
    "downvote" integer DEFAULT 0 ,
    "last_date_edit" text DEFAULT now()::text NOT NULL
)
WITH (oids = false);

CREATE TABLE "public"."exempleproject_chat" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "session_id" character varying(255) NOT NULL,
    "message" jsonb NOT NULL,
    "upvote" integer DEFAULT 0 ,
    "downvote" integer DEFAULT 0 ,
    CONSTRAINT "exempleproject_chat_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE TABLE "public"."exempleproject_chat_evaluation" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_id" character varying(255) NOT NULL UNIQUE,
    "rating_relevance" smallint NOT NULL CHECK ("rating_relevance" BETWEEN 1 AND 5),
    "rating_accuracy" smallint NOT NULL CHECK ("rating_accuracy" BETWEEN 1 AND 5),
    "rating_clarity" smallint NOT NULL CHECK ("rating_clarity" BETWEEN 1 AND 5),
    "rating_completeness" smallint NOT NULL CHECK ("rating_completeness" BETWEEN 1 AND 5),
    "rating_helpfulness" smallint NOT NULL CHECK ("rating_helpfulness" BETWEEN 1 AND 5),
    "rating_global" numeric(3,2) GENERATED ALWAYS AS (
        round((
            "rating_relevance" +
            "rating_accuracy" +
            "rating_clarity" +
            "rating_completeness" +
            "rating_helpfulness"
        )::numeric / 5, 2)
    ) STORED,
    "comment" text,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "updated_at" timestamptz DEFAULT now() NOT NULL
)
WITH (oids = false);

CREATE TABLE "public"."project" (
    "uuid" text NOT NULL,
    "project_name" text,
    "project_nameslug" text,
    "last_date_edit" text DEFAULT now()::text NOT NULL
)
WITH (oids = false);
